### ISSUE TITLE
Can't import in unity 2019.4.29f1

### ISSUE THREAD

**Issue by parkouristik93** [acertainbluecat/VRCPlayersOnlyMirror#1]
Putting the checkmark on all but it automatically removes.
![image](https://user-images.githubusercontent.com/22059952/131244753-0e2bac67-ca35-4408-9d87-161c47a9061a.png)

**Comment by acertainbluecat** [comment]
Are you sure you don't already have it imported in the project? The lack of indicators on the right side implies the files already exist in the project and are unchanged, except for the udon program asset. This behavior seems consistent with what happens when you import a unity package and there are assets that already exist in the project that are identical. I can import into a fresh 2019.4.29f1 project just fine.
